-- 
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/26/2022 4:28:55 PM
-- Source server version: 8.0.26
-- Source connection string: User Id=root;Host=localhost;Character Set=utf8;HTTP Base64=False
-- Target server version: 8.0.26
-- Target connection string: User Id=root;Host=localhost;Character Set=utf8;HTTP Base64=False
-- Run this script against test to synchronize it with pg_new
-- 

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

DROP DATABASE pg_business;

SET NAMES 'utf8';

CREATE DATABASE pg_business;

--
-- Set default database
--
USE pg_business;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id CHAR(36) NOT NULL,
  role INT NOT NULL,
  user_name VARCHAR(50) NULL,
  phone VARCHAR(20) NOT NULL,
  id_number VARCHAR(20) DEFAULT NULL,
  birth_date DATE DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `manager`
--
CREATE TABLE manager (
  user_id CHAR(36) NOT NULL,
  licence datetime NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE manager 
  ADD CONSTRAINT FKmanager594358 FOREIGN KEY (user_id)
    REFERENCES user(user_id);

--
-- Create table `employee`
--
CREATE TABLE employee (
  user_id CHAR(36) NOT NULL,
  hourly_wage DECIMAL(19, 4) DEFAULT NULL,
  salary DECIMAL(19, 4) DEFAULT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE employee 
  ADD CONSTRAINT FKemployee803997 FOREIGN KEY (user_id)
    REFERENCES USER(user_id);

--
-- Create table `customer`
--
CREATE TABLE customer (
  user_id CHAR(36) NOT NULL,
  `rank` INT DEFAULT NULL,
  `point` INT DEFAULT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE customer 
  ADD CONSTRAINT customer_ibfk_1 FOREIGN KEY (user_id)
    REFERENCES user(user_id);


--
-- Create table `table_reservation`
--
CREATE TABLE table_reservation (
  table_reservation_id CHAR(36) NOT NULL,
  time_reservation datetime NOT NULL,
  employee_id CHAR(36) NOT NULL,
  customer_id CHAR(36) NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (table_reservation_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE table_reservation 
  ADD CONSTRAINT FKtable_rese240763 FOREIGN KEY (employee_id)
    REFERENCES employee(user_id);

ALTER TABLE table_reservation 
  ADD CONSTRAINT FKtable_customer FOREIGN KEY (customer_id)
    REFERENCES customer(user_id);

--
-- Create table `invoice`
--
CREATE TABLE invoice (
  invoice_id CHAR(36) NOT NULL,
  payment_type INT DEFAULT NULL,
  payment_time datetime DEFAULT NULL,
  total DECIMAL(19, 4) DEFAULT NULL,
  employee_id CHAR(36) NOT NULL,
  customer_id CHAR(36) NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE invoice 
  ADD CONSTRAINT FKinvoice342976 FOREIGN KEY (employee_id)
    REFERENCES employee(user_id);

ALTER TABLE invoice 
  ADD CONSTRAINT FKinvoice_customer FOREIGN KEY (customer_id)
    REFERENCES customer(user_id);

--
-- Create table `account`
--
CREATE TABLE account (
  account_id CHAR(36) NOT NULL,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(255) NOT NULL,
  salt varchar(255) NOT NULL,
  user_id CHAR(36) NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE account 
  ADD CONSTRAINT FKaccount986853 FOREIGN KEY (user_id)
    REFERENCES user(user_id);

--
-- Create table `shift`
--
CREATE TABLE shift (
  shift_id CHAR(36) NOT NULL,
  time_start INT NOT NULL,
  time_end INT NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (shift_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `shift_worked`
--
CREATE TABLE shift_worked (
  shift_worked_id CHAR(36) NOT NULL,
  time_join datetime NOT NULL,
  time_left datetime NOT NULL,
  date_worked DATE DEFAULT NULL,
  shift_wage DECIMAL(19, 4) DEFAULT NULL,
  employe_id CHAR(36) NOT NULL,
  shift_id CHAR(36) NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (shift_worked_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE shift_worked 
  ADD CONSTRAINT FKshift_work739989 FOREIGN KEY (employe_id)
    REFERENCES employee(user_id);

--
-- Create foreign key
--
ALTER TABLE shift_worked 
  ADD CONSTRAINT FKshift_work943459 FOREIGN KEY (shift_id)
    REFERENCES shift(shift_id);

--
-- Create table `table`
--
CREATE TABLE `table` (
  table_id CHAR(36) NOT NULL,
  floor INT NOT NULL,
  table_name VARCHAR(20) NOT NULL,
  max_size INT DEFAULT NULL,
  table_status INT DEFAULT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (table_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `dish`
--
CREATE TABLE dish (
  dish_id CHAR(36) NOT NULL,
  dish_name VARCHAR(50) NOT NULL,
  dish_type INT NOT NULL,
  price DECIMAL(19, 4) DEFAULT NULL,
  dish_status INT DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (dish_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `order`
--
CREATE TABLE `order` (
  order_id CHAR(36) NOT NULL,
  table_id CHAR(36) NOT NULL,
  invoice_id CHAR(36) DEFAULT NULL,
  table_reservation_id CHAR(36) DEFAULT NULL,
  order_time datetime DEFAULT CURRENT_TIMESTAMP,
  customer_name varchar(50) DEFAULT NULL,
  customer_phone varchar(20) DEFAULT NULL,
  paid bit(1) DEFAULT b'0',
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE `order` 
  ADD CONSTRAINT FKorder_dish260493 FOREIGN KEY (table_reservation_id)
    REFERENCES table_reservation(table_reservation_id);

--
-- Create foreign key
--
ALTER TABLE `order` 
  ADD CONSTRAINT FKorder_dish72080 FOREIGN KEY (invoice_id)
    REFERENCES invoice(invoice_id);

--
-- Create foreign key
--
ALTER TABLE `order` 
  ADD CONSTRAINT FKorder_dish791179 FOREIGN KEY (table_id)
    REFERENCES `table`(table_id);


--
-- Create table `order_dish`
--
CREATE TABLE order_dish (
  dish_order_id CHAR(36) NOT NULL,
  quantity INT NOT NULL,
  dish_id CHAR(36) NOT NULL,
  order_id CHAR(36) NOT NULL,
  created_by VARCHAR(20) DEFAULT NULL,
  update_by VARCHAR(20) DEFAULT NULL,
  created_date datetime DEFAULT CURRENT_TIMESTAMP,
  update_date datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (dish_order_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE order_dish 
  ADD CONSTRAINT FKorder_dish923515 FOREIGN KEY (dish_id)
    REFERENCES dish(dish_id);


ALTER TABLE order_dish 
  ADD CONSTRAINT FK_Order FOREIGN KEY (order_id)
    REFERENCES `order`(order_id);
--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;